controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_recetas_recientes:
    path: '/api/recetas/recientes'
    controller: 'App\Controller\RecetaController::getRecientes'
    methods: ['GET']